set(CPACK_PACKAGE_NAME "zportal")
set(CPACK_PACKAGE_VENDOR "Wiktor Sołtys")
set(CPACK_PACKAGE_CONTACT "wiesiekdx@gmail.com")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "ZPortal: TUN/IP tunnel over TCP with optional SOCKS5 chain")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/sweet-bbq-sauce/zportal")

set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

set(CPACK_GENERATOR "TGZ;DEB")

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Wiktor Sołtys")
set(CPACK_DEBIAN_PACKAGE_SECTION "net")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_HOST_SYSTEM_PROCESSOR}")

include(CPack)